aula8Exercicio3.1: limpa funcoesAVL.o aula8Exercicio3.1.c 
	gcc funcoesAVL.o aula8Exercicio3.1.c -o aula8Exercicio3.1 -Wall;./aula8Exercicio3.1

aula8Exercicio3.2: limpa funcoesAVL.o aula8Exercicio3.2.c
	gcc funcoesAVL.o aula8Exercicio3.2.c -o aula8Exercicio3.2 -Wall;./aula8Exercicio3.2

funcoes_bib.o: funcoesAVL.c
	gcc -c funcoesAVL.c -Wall

limpa: 	
	rm -f *.o